export const BOOKING_CONFIG = {
  hotelId: 'vintagevallyresort',
  bookingUrl: 'https://live.ipms247.com/booking/book-rooms-vintagevallyresort',
  externalResources: {
    jquery: 'https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js',
    css: [
      'https://live.ipms247.com/themes/reservation/css/bookingbtn/resui_datepicker.css',
      'https://live.ipms247.com/themes/reservation/css/bookingbtn/resui_bookingbox.css',
    ],
    js: [
      'https://live.ipms247.com/themes/reservation/js/bookingbtn/jquery-ui.js',
      'https://live.ipms247.com/themes/reservation/js/bookingbtn/common.js',
      'https://live.ipms247.com/themes/reservation/js/bookingbtn/resui_resbookingbox.js',
    ],
  },
  defaultParams: {
    adults: 2,
    children: 0,
  },
  widgetOptions: {
    btnContainer: 'bb_resBookingBox',
    headerColor: '#56c5d0',
    bodyColor: 'rgba(0, 0, 0, 0.74)',
    showborder: false,
    BorderColor: 'rgba(0, 0, 0, 0.74)',
    BorderWidth: 2,
    BorderType: 'solid',
    FontFamily: 'Arial, Helvetica, sans-serif',
    BodyLanguage: 'en',
    FontSize: '12',
    TextColor: '#fff',
    InputBorderColor: '#000',
    InputbackColor: '#fff',
    InputTextColor: '#000',
    ButnBackColor: '#cd8a0a',
    ButnBorderColor: '#cd8a0a',
    ButnTextColor: '#fff',
    HeaderTextColor: '#000000',
    HeaderFontSize: '15',
    ShowHeader: '0',
    boxwidth: '100',
    boxwidthtype: 'TYPE_PER',
    ShowInlineCSS: '1',
    type: 'htype',
    acr: false,
    ShowChild: false,
    rooms: false,
    promotion: false,
    defaultadult: 10,
    defaultchild: 10,
    defaultroom: 16,
    ShowNights: false,
    Nonights: 15,
    HTextCaption: 'Reservation',
    BtnTextCaption: 'Book Now',
    LblPromoCaption: 'Promotion',
    LblChkOutCaption: 'Check Out',
    Calinit: true,
    CalShowOn: 'both',
    CalDefaultDt: '+0w',
    CalChangeMonth: true,
    CalMinDate: '0',
    CalMaxDate: '',
    CalDtFormat: 'dd-mm-yy',
    CalCutoffDays: '1',
    CalImage: '1px -24px',
    CalBackColor: '#a0f2ea',
    CalHeaderColor: '#F9E8E0',
    CalCellActiveColor: '#101414',
    CalCellInActiveColor: '#c8dbda',
    LblArrivalCaption: 'Check In',
    LblNightsCaption: 'Nights',
    LblAdultsCaption: 'Adult',
    LblChildsCaption: 'Child',
    LblRoomsCaption: 'Rooms',
    LblPerRoomCaption: 'Per Room',
    HotelId: 'vintagevallyresort',
  },
};
